name: Package and Release Resource Pack or Data Pack

on:
  workflow_call:
    inputs:
      file_name:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  package:
    runs-on: ubuntu-latest

    outputs:
      zip_name: ${{ steps.zip.outputs.zip_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP
        id: zip
        run: |
          ZIP_NAME="${{ inputs.file_name }}.zip"
          zip -r "${ZIP_NAME}" pack.mcmeta pack.png assets data
          echo "zip_name=${ZIP_NAME}" >> $GITHUB_OUTPUT
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-asset
          path: ${{ steps.zip.outputs.zip_name }}

  release:
    needs: package
    permissions:
      contents: write
    uses: ./.github/workflows/release-core.yaml
    with:
      version: ${{ inputs.version }}
      asset_path: ${{ needs.package.outputs.zip_name }}
      asset_name: ${{ needs.package.outputs.zip_name }}
    secrets:
      token: ${{ secrets.token }}